# Generated by Django 2.1 on 2019-08-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guicolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='photo',
            field=models.ImageField(null=True, upload_to='staticfiles/images'),
        ),
        migrations.AddField(
            model_name='tour',
            name='map',
            field=models.ImageField(null=True, upload_to='staticfiles/images'),
        ),
    ]
