# Generated by Django 2.1 on 2019-08-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guicolapp', '0002_auto_20190818_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
