# Generated by Django 2.1 on 2019-08-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guicolapp', '0003_auto_20190818_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='guia',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/guia'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tour',
            name='map',
            field=models.ImageField(null=True, upload_to='images/tour'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
