# Generated by Django 2.1 on 2019-09-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guicolapp', '0004_auto_20190829_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='photo',
            field=models.ImageField(null=True, upload_to='guias'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='map',
            field=models.ImageField(null=True, upload_to='maps'),
        ),
    ]
